---
name: Node.js Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          registry-url: https://registry.npmjs.org/
      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
      - run: pnpm install
      - run: pnpm release
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}