---
name: Node.js Package (next tag)

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - run: pnpm test
      - run: |
          pnpm version prerelease --no-git-tag-version \
            --preid=`git rev-parse --short HEAD`
          pnpm release -- --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}